export const users = [
  {
    id: 1,
    name: "Aarav Sharma",
    email: "employee1@me.com",
    password: "123",
    role: "employee",
    tasks: [
      {
        id: 1,
        title: "Fix login bug",
        description: "Resolve login issue.",
        date: "2026-03-01",
        category: "Development",
        status: "active",
      },
      {
        id: 2,
        title: "Update dashboard UI",
        description: "Improve UI responsiveness.",
        date: "2026-03-02",
        category: "Design",
        status: "completed",
      },
      {
        id: 3,
        title: "Refactor auth code",
        description: "Clean authentication logic.",
        date: "2026-03-03",
        category: "Development",
        status: "active",
      },
      {
        id: 4,
        title: "Write unit tests",
        description: "Increase test coverage.",
        date: "2026-03-04",
        category: "Testing",
        status: "active",
      },
      {
        id: 5,
        title: "Fix CSS issues",
        description: "Resolve layout bugs.",
        date: "2026-03-05",
        category: "Frontend",
        status: "completed",
      },
      {
        id: 6,
        title: "API integration",
        description: "Connect dashboard APIs.",
        date: "2026-03-06",
        category: "Backend",
        status: "active",
      },
      {
        id: 7,
        title: "Improve performance",
        description: "Optimize rendering.",
        date: "2026-03-07",
        category: "Optimization",
        status: "completed",
      },
      {
        id: 8,
        title: "Error handling",
        description: "Add global error handling.",
        date: "2026-03-08",
        category: "Development",
        status: "active",
      },
      {
        id: 9,
        title: "Form validation",
        description: "Add form validations.",
        date: "2026-03-09",
        category: "Frontend",
        status: "active",
      },
      {
        id: 10,
        title: "Accessibility fixes",
        description: "Improve accessibility.",
        date: "2026-03-10",
        category: "UX",
        status: "completed",
      },
    ],
  },

  {
    id: 2,
    name: "Priya Verma",
    email: "employee2@me.com",
    password: "123",
    role: "employee",
    tasks: [
      {
        id: 1,
        title: "Create landing page",
        description: "Build landing page in React.",
        date: "2026-03-01",
        category: "Frontend",
        status: "active",
      },
      {
        id: 2,
        title: "Database optimization",
        description: "Improve query performance.",
        date: "2026-03-02",
        category: "Backend",
        status: "completed",
      },
      {
        id: 3,
        title: "Navbar component",
        description: "Reusable navbar.",
        date: "2026-03-03",
        category: "Frontend",
        status: "active",
      },
      {
        id: 4,
        title: "Fix mobile layout",
        description: "Responsive fixes.",
        date: "2026-03-04",
        category: "Design",
        status: "completed",
      },
      {
        id: 5,
        title: "Add animations",
        description: "Page animations.",
        date: "2026-03-05",
        category: "UI",
        status: "active",
      },
      {
        id: 6,
        title: "Form handling",
        description: "React Hook Form setup.",
        date: "2026-03-06",
        category: "Frontend",
        status: "completed",
      },
      {
        id: 7,
        title: "API caching",
        description: "Implement caching.",
        date: "2026-03-07",
        category: "Backend",
        status: "active",
      },
      {
        id: 8,
        title: "Search feature",
        description: "Add search functionality.",
        date: "2026-03-08",
        category: "Frontend",
        status: "active",
      },
      {
        id: 9,
        title: "SEO improvements",
        description: "Meta tags optimization.",
        date: "2026-03-09",
        category: "Marketing",
        status: "completed",
      },
      {
        id: 10,
        title: "Dark mode",
        description: "Implement theme toggle.",
        date: "2026-03-10",
        category: "UI",
        status: "active",
      },
    ],
  },

  {
    id: 3,
    name: "Rohan Mehta",
    email: "employee3@me.com",
    password: "123",
    role: "employee",
    tasks: [
      {
        id: 1,
        title: "Implement JWT auth",
        description: "Secure APIs.",
        date: "2026-03-01",
        category: "Security",
        status: "completed",
      },
      {
        id: 2,
        title: "Setup CI/CD",
        description: "Auto deployment.",
        date: "2026-03-02",
        category: "DevOps",
        status: "active",
      },
      {
        id: 3,
        title: "Docker setup",
        description: "Containerize app.",
        date: "2026-03-03",
        category: "DevOps",
        status: "active",
      },
      {
        id: 4,
        title: "Rate limiting",
        description: "Prevent API abuse.",
        date: "2026-03-04",
        category: "Security",
        status: "completed",
      },
      {
        id: 5,
        title: "Logging system",
        description: "Add centralized logs.",
        date: "2026-03-05",
        category: "Backend",
        status: "active",
      },
      {
        id: 6,
        title: "Environment config",
        description: "Manage env variables.",
        date: "2026-03-06",
        category: "DevOps",
        status: "completed",
      },
      {
        id: 7,
        title: "Backup scripts",
        description: "Database backups.",
        date: "2026-03-07",
        category: "Backend",
        status: "active",
      },
      {
        id: 8,
        title: "Load balancing",
        description: "Scale services.",
        date: "2026-03-08",
        category: "Infrastructure",
        status: "active",
      },
      {
        id: 9,
        title: "Server monitoring",
        description: "Track uptime.",
        date: "2026-03-09",
        category: "DevOps",
        status: "completed",
      },
      {
        id: 10,
        title: "Security audit",
        description: "Check vulnerabilities.",
        date: "2026-03-10",
        category: "Security",
        status: "active",
      },
    ],
  },

  {
    id: 4,
    name: "Neha Kapoor",
    email: "employee4@me.com",
    password: "123",
    role: "employee",
    tasks: [
      {
        id: 1,
        title: "Client meeting",
        description: "Discuss features.",
        date: "2026-03-01",
        category: "Management",
        status: "active",
      },
      {
        id: 2,
        title: "Prepare report",
        description: "Weekly progress.",
        date: "2026-03-02",
        category: "Management",
        status: "completed",
      },
      {
        id: 3,
        title: "Team standup",
        description: "Daily sync.",
        date: "2026-03-03",
        category: "Management",
        status: "active",
      },
      {
        id: 4,
        title: "Sprint planning",
        description: "Plan next sprint.",
        date: "2026-03-04",
        category: "Management",
        status: "completed",
      },
      {
        id: 5,
        title: "Review PRs",
        description: "Code reviews.",
        date: "2026-03-05",
        category: "Management",
        status: "active",
      },
      {
        id: 6,
        title: "Client feedback",
        description: "Collect feedback.",
        date: "2026-03-06",
        category: "Management",
        status: "active",
      },
      {
        id: 7,
        title: "Project roadmap",
        description: "Future planning.",
        date: "2026-03-07",
        category: "Management",
        status: "completed",
      },
      {
        id: 8,
        title: "Documentation",
        description: "Update docs.",
        date: "2026-03-08",
        category: "Documentation",
        status: "active",
      },
      {
        id: 9,
        title: "Team review",
        description: "Performance review.",
        date: "2026-03-09",
        category: "Management",
        status: "completed",
      },
      {
        id: 10,
        title: "Budget planning",
        description: "Resource allocation.",
        date: "2026-03-10",
        category: "Management",
        status: "active",
      },
    ],
  },

  {
    id: 5,
    name: "Vikram Singh",
    email: "employee5@me.com",
    password: "123",
    role: "employee",
    tasks: [
      {
        id: 1,
        title: "SEO optimization",
        description: "Improve ranking.",
        date: "2026-03-01",
        category: "Marketing",
        status: "active",
      },
      {
        id: 2,
        title: "Keyword research",
        description: "Find target keywords.",
        date: "2026-03-02",
        category: "Marketing",
        status: "completed",
      },
      {
        id: 3,
        title: "Blog writing",
        description: "Write SEO blogs.",
        date: "2026-03-03",
        category: "Content",
        status: "active",
      },
      {
        id: 4,
        title: "Google Ads",
        description: "Run ad campaign.",
        date: "2026-03-04",
        category: "Marketing",
        status: "completed",
      },
      {
        id: 5,
        title: "Analytics review",
        description: "Track traffic.",
        date: "2026-03-05",
        category: "Analytics",
        status: "active",
      },
      {
        id: 6,
        title: "Email campaign",
        description: "Send newsletters.",
        date: "2026-03-06",
        category: "Marketing",
        status: "completed",
      },
      {
        id: 7,
        title: "Social media plan",
        description: "Plan posts.",
        date: "2026-03-07",
        category: "Marketing",
        status: "active",
      },
      {
        id: 8,
        title: "Competitor research",
        description: "Analyze competitors.",
        date: "2026-03-08",
        category: "Research",
        status: "active",
      },
      {
        id: 9,
        title: "Backlink building",
        description: "SEO backlinks.",
        date: "2026-03-09",
        category: "SEO",
        status: "completed",
      },
      {
        id: 10,
        title: "Content strategy",
        description: "Plan content.",
        date: "2026-03-10",
        category: "Marketing",
        status: "active",
      },
    ],
  },

  {
    id: 6,
    name: "Ananya Gupta",
    email: "employee6@me.com",
    password: "123",
    role: "employee",
    tasks: [
      {
        id: 1,
        title: "User profile page",
        description: "Build profile UI.",
        date: "2026-03-01",
        category: "Frontend",
        status: "active",
      },
      {
        id: 2,
        title: "Avatar upload",
        description: "Implement profile image upload.",
        date: "2026-03-02",
        category: "Frontend",
        status: "completed",
      },
      {
        id: 3,
        title: "Password reset",
        description: "Forgot password flow.",
        date: "2026-03-03",
        category: "Backend",
        status: "active",
      },
      {
        id: 4,
        title: "Notification UI",
        description: "Design notification component.",
        date: "2026-03-04",
        category: "UI",
        status: "completed",
      },
      {
        id: 5,
        title: "Settings page",
        description: "Create user settings page.",
        date: "2026-03-05",
        category: "Frontend",
        status: "active",
      },
      {
        id: 6,
        title: "API validation",
        description: "Validate API responses.",
        date: "2026-03-06",
        category: "Backend",
        status: "active",
      },
      {
        id: 7,
        title: "Accessibility review",
        description: "Improve accessibility.",
        date: "2026-03-07",
        category: "UX",
        status: "completed",
      },
      {
        id: 8,
        title: "Profile edit form",
        description: "Edit profile feature.",
        date: "2026-03-08",
        category: "Frontend",
        status: "active",
      },
      {
        id: 9,
        title: "Toast notifications",
        description: "Add alert messages.",
        date: "2026-03-09",
        category: "UI",
        status: "active",
      },
      {
        id: 10,
        title: "Error states",
        description: "Handle error UI states.",
        date: "2026-03-10",
        category: "Frontend",
        status: "completed",
      },
    ],
  },

  {
    id: 7,
    name: "Rahul Khanna",
    email: "employee7@me.com",
    password: "123",
    role: "employee",
    tasks: [
      {
        id: 1,
        title: "API documentation",
        description: "Write API docs.",
        date: "2026-03-01",
        category: "Documentation",
        status: "active",
      },
      {
        id: 2,
        title: "Swagger setup",
        description: "Integrate Swagger.",
        date: "2026-03-02",
        category: "Backend",
        status: "completed",
      },
      {
        id: 3,
        title: "Payment gateway",
        description: "Integrate Stripe.",
        date: "2026-03-03",
        category: "Backend",
        status: "active",
      },
      {
        id: 4,
        title: "Invoice generator",
        description: "Generate PDF invoices.",
        date: "2026-03-04",
        category: "Backend",
        status: "active",
      },
      {
        id: 5,
        title: "Webhook listener",
        description: "Handle payment events.",
        date: "2026-03-05",
        category: "Backend",
        status: "completed",
      },
      {
        id: 6,
        title: "Refund logic",
        description: "Implement refunds.",
        date: "2026-03-06",
        category: "Backend",
        status: "active",
      },
      {
        id: 7,
        title: "Transaction logs",
        description: "Store payment logs.",
        date: "2026-03-07",
        category: "Database",
        status: "completed",
      },
      {
        id: 8,
        title: "Retry mechanism",
        description: "Retry failed payments.",
        date: "2026-03-08",
        category: "Backend",
        status: "active",
      },
      {
        id: 9,
        title: "Security checks",
        description: "Validate payment requests.",
        date: "2026-03-09",
        category: "Security",
        status: "completed",
      },
      {
        id: 10,
        title: "Performance testing",
        description: "Test payment API load.",
        date: "2026-03-10",
        category: "Testing",
        status: "active",
      },
    ],
  },

  {
    id: 8,
    name: "Simran Kaur",
    email: "employee8@me.com",
    password: "123",
    role: "employee",
    tasks: [
      {
        id: 1,
        title: "Dashboard charts",
        description: "Add analytics charts.",
        date: "2026-03-01",
        category: "Frontend",
        status: "active",
      },
      {
        id: 2,
        title: "Chart.js setup",
        description: "Integrate chart library.",
        date: "2026-03-02",
        category: "Frontend",
        status: "completed",
      },
      {
        id: 3,
        title: "Analytics API",
        description: "Create analytics endpoint.",
        date: "2026-03-03",
        category: "Backend",
        status: "active",
      },
      {
        id: 4,
        title: "Filter reports",
        description: "Filter by date range.",
        date: "2026-03-04",
        category: "Frontend",
        status: "completed",
      },
      {
        id: 5,
        title: "Export CSV",
        description: "Download reports.",
        date: "2026-03-05",
        category: "Backend",
        status: "active",
      },
      {
        id: 6,
        title: "Data aggregation",
        description: "Summarize metrics.",
        date: "2026-03-06",
        category: "Database",
        status: "completed",
      },
      {
        id: 7,
        title: "User analytics",
        description: "Track user activity.",
        date: "2026-03-07",
        category: "Analytics",
        status: "active",
      },
      {
        id: 8,
        title: "Performance graphs",
        description: "Add performance charts.",
        date: "2026-03-08",
        category: "Frontend",
        status: "active",
      },
      {
        id: 9,
        title: "Report scheduler",
        description: "Schedule reports.",
        date: "2026-03-09",
        category: "Backend",
        status: "completed",
      },
      {
        id: 10,
        title: "UI polish",
        description: "Improve chart styles.",
        date: "2026-03-10",
        category: "Design",
        status: "active",
      },
    ],
  },

  {
    id: 9,
    name: "System Admin",
    email: "admin@me.com",
    password: "123",
    role: "admin",
    tasks: [],
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("users", JSON.stringify(users));
};
